// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var default_site, input, search, sites;
    default_site = "g";
    sites = {
      "g": function(query) {
        return "https://www.google.fr/search?q=" + query;
      },
      "w": function(query) {
        return "http://fr.wikipedia.org/w/index.php?search=" + query;
      },
      "yt": function(query) {
        return "https://www.youtube.com/results?search_query=" + query;
      },
      "ddg": function(query) {
        return "https://duckduckgo.com/?q=" + query;
      },
      "soundcloud": function(query) {
        return "https://soundcloud.com/search?q=" + query;
      },
      "sc": function(query) {
        return "https://soundcloud.com/search?q=" + query;
      }
    };
    console.log("sites");
    console.log(sites);
    search = function(input) {
      var bang, i, part, parts, _i, _len;
      parts = input.split(/\ +/);
      console.log("parts");
      console.log(parts);
      for (i = _i = 0, _len = parts.length; _i < _len; i = ++_i) {
        part = parts[i];
        if (part.charAt(0) !== "!") {
          continue;
        }
        bang = part.substring(1);
        if (!sites[bang]) {
          continue;
        }
        parts.splice(i, 1);
        console.log(sites[bang](parts.join("+")));
        window.location.href = sites[bang](parts.join("+"));
        return;
      }
      console.log(sites[default_site](parts.join("+")));
      return window.location.href = sites[default_site](parts.join("+"));
    };
    input = window.location.search;
    if (input && input.charAt(0) === "?" && input.charAt(1) === "q" && input.charAt(2) === "=") {
      search(input.substring(3).replace(/\+/g, " "));
    } else {
      $("#search_input").focus();
    }
    $("#search_button").click(function() {
      return search($("#search_input").val());
    });
    return $("#search_input").keypress(function(e) {
      if (e.keyCode === 13) {
        return search($("#search_input").val());
      }
    });
  });

}).call(this);
