// Generated by CoffeeScript 1.7.1
(function() {
  var alias, bang, button, default_site, do_search, encoding, encodings, f, input, p, query, site, sites, template, _fn;

  sites = {
    "google": function(query) {
      return "https://www.google.fr/search?q=" + query;
    },
    "google.com": function(query) {
      return "https://www.google.com/search?q=" + query;
    },
    "wikipedia": function(query) {
      return "http://fr.wikipedia.org/w/index.php?search=" + query;
    },
    "wikipedia.com": function(query) {
      return "http://www.wikipedia.org/w/index.php?search=" + query;
    },
    "youtube": function(query) {
      return "https://www.youtube.com/results?search_query=" + query;
    },
    "duckduckgo": function(query) {
      return "https://duckduckgo.com/?q=" + query;
    },
    "soundcloud": function(query) {
      return "https://soundcloud.com/search?q=" + query;
    },
    "deezer": function(query) {
      return "http://deezer.com/fr/search/" + query;
    },
    "thepiratebay": function(query) {
      return "http://thepiratebay.cr/search/" + query + "/0/7/0";
    }
  };

  encodings = {
    "google": function(words) {
      return words.join("+");
    },
    "google.com": function(words) {
      return words.join("+");
    },
    "wikipedia": function(words) {
      return words.join("+");
    },
    "wikipedia.com": function(words) {
      return words.join("+");
    },
    "youtube": function(words) {
      return words.join("+");
    },
    "duckduckgo": function(words) {
      return words.join("+");
    },
    "soundcloud": function(words) {
      return words.join("+");
    },
    "deezer": function(words) {
      return words.join("+");
    },
    "thepiratebay": function(words) {
      return words.join(" ");
    }
  };

  alias = {
    "g": "google",
    "gfr": "google",
    "gus": "google.com",
    "w": "wikipedia",
    "wfr": "wikipedia",
    "wus": "wikipedia.com",
    "ddg": "duckduckgo",
    "sc": "soundcloud",
    "yt": "youtube",
    "dz": "deezer",
    "tpb": "thepiratebay"
  };

  default_site = "google";

  template = sites[default_site];

  encoding = encodings[default_site];

  do_search = function(sentence) {
    var bang, index, site, word, words, _i, _len;
    words = sentence.split(/\s+/);
    index = 0;
    for (_i = 0, _len = words.length; _i < _len; _i++) {
      word = words[_i];
      for (bang in alias) {
        site = alias[bang];
        if (word === ('!' + bang) || word === ('!' + site)) {
          template = sites[site];
          encoding = encodings[site];
          words.splice(index, 1);
        }
      }
      index++;
    }
    return window.location.href = template(encoding(words));
  };

  input = window.location.search;

  if (input && input.match(/^\?q=/)) {
    query = input.substring(3).replace(/\/$/, '').replace(/\+/g, ' ');
    console.log(decodeURIComponent(query));
    do_search(decodeURIComponent(query));
  }

  _fn = function(site) {
    return button.addEventListener("click", function() {
      document.querySelector("#query input").value += " !" + site;
      return document.querySelector("#submit").click();
    });
  };
  for (site in sites) {
    f = sites[site];
    button = document.createElement('button');
    button.appendChild(document.createTextNode(site));
    _fn(site);
    document.querySelector('#bangs').appendChild(button);
  }

  for (bang in alias) {
    site = alias[bang];
    p = document.createElement('p');
    p.appendChild(document.createTextNode("!" + bang));
    p.className = "alias";
    document.querySelector('#alias').appendChild(p);
  }

  document.querySelector("#query input").value = "";

}).call(this);
